using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DevBootstrapper.Controllers;
using DevTrends.MvcDonutCaching;
using DevBootstrapper.Models.Context;
using DevBootstrapper.Models.EntityModel.POCO;

namespace DevBootstrapper.Controllers
{
    public class EmployeesController : GenericController<NorthwindEntities> {

		#region Developer Comments - Alim Ul karim
        /*
         *  Generated by Alim Ul Karim on behalf of Developers Organism.
         *  Find us developers-organism.com
         *  https://fb.com/DevelopersOrganism
         *  mailto:alim@developers-organism.com	
         *  Google 'https://www.google.com.bd/search?q=Alim-ul-karim'
         *  First Written : 23 March 2014
         *  Modified      : 03 March 2015
         * * */
		#endregion

		#region Constants

		const string DeletedError = "Sorry for the inconvenience, last record is not removed. Please be in touch with admin.";
		const string DeletedSaved = "Removed successfully.";
		const string EditedSaved = "Modified successfully.";
		const string EditedError = "Sorry for the inconvenience, transaction is failed to save into the database. Please be in touch with admin.";
		const string CreatedError = "Sorry for the inconvenience, couldn't create the last transaction record.";
		const string CreatedSaved = "Transaction is successfully added to the database.";
		const string ControllerName = "Employees";
		///Constant value for where the controller is actually visible.
		const string ControllerVisibleUrl = "/Employees/";
        const string CurrentControllerRemoveOutputCacheUrl = "/Partials/GetEmployeeID";

		#endregion

		#region Enums

		internal enum ViewStates {
            Index,
            Create,
            CreatePostBefore,
            CreatePostAfter,
            Edit,
            EditPostBefore,
            EditPostAfter,
            Details,
            Delete,
            DeletePost
        }

		#endregion

		#region Constructors
		
		public EmployeesController(): base(true){
			ViewBag.controller = ControllerName;
            ViewBag.visibleUrl = ControllerVisibleUrl;
		} 

		#endregion
		
		#region View tapping
		/// <summary>
        /// Always tap once before going into the view.
        /// </summary>
        /// <param name="view">Say the view state, where it is calling from.</param>
        /// <param name="employee">Gives the model if it is a editing state or creating posting state or when deleting.</param>
        /// <returns>If successfully saved returns true or else false.</returns>
		bool ViewTapping(ViewStates view, Employee employee = null, bool entityValidState = true){
			switch (view){
				case ViewStates.Index:
					break;
				case ViewStates.Create:
					break;
				case ViewStates.CreatePostBefore: // before saving it
					break;
                case ViewStates.CreatePostAfter: // after saving
					break;
				case ViewStates.Edit:
					break;
				case ViewStates.Details:
					break;
				case ViewStates.EditPostBefore: // before saving it
					break;
                case ViewStates.EditPostAfter: // after saving
					break;
				case ViewStates.Delete:
					break;
			}
			return true;
		}
		#endregion

		#region Save database common method

		/// <summary>
        /// Better approach to save things into database(than db.SaveChanges()) for this controller.
        /// </summary>
        /// <param name="view">Say the view state, where it is calling from.</param>
        /// <param name="employee">Your model information to send in email to developer when failed to save.</param>
        /// <returns>If successfully saved returns true or else false.</returns>
		bool SaveDatabase(ViewStates view, Employee employee = null){
			// working those at HttpPost time.
			switch (view){
				case ViewStates.Create:
					break;
				case ViewStates.Edit:
					break;
				case ViewStates.Delete:
					break;
			}

			try	{                
				var changes = db.SaveChanges(employee);
				if(changes > 0){
                    RemoveOutputCacheOnIndex();
                    RemoveOutputCache(CurrentControllerRemoveOutputCacheUrl);
					return true;
				}
			} catch (Exception ex){
				 throw new Exception("Message : " + ex.Message.ToString() + " Inner Message : " + ex.InnerException.Message.ToString());
			}
			return false;
		}
		#endregion

		#region DropDowns Generate

        #region EmployeesController : DropDowns to paste into the partial
            
            // [DonutOutputCache(CacheProfile = "YearNoParam")]
            public JsonResult GetReportsTo() {
                var data = db.Employees.Select(n => new {id = n.EmployeeID, value = n.LastName}).ToList();
                return Json(data, JsonRequestBehavior.AllowGet);
            }
      
        #endregion

		public void GetDropDowns(Employee employee = null){
			if(employee != null){
				ViewBag.ReportsTo = new SelectList(db.Employees.ToList(), "EmployeeID", "LastName", employee.ReportsTo);
			} else {			
				ViewBag.ReportsTo = new SelectList(db.Employees.ToList(), "EmployeeID", "LastName");
			}
			
		}

		public void GetDropDowns(System.Int32 id){			
				ViewBag.ReportsTo = new SelectList(db.Employees.ToList(), "EmployeeID", "LastName");
		}
		#endregion

		#region Index
        [OutputCache(CacheProfile = "Year")]
        public ActionResult Index() { 
        
            var employees = db.Employees.Include(e => e.Employee2);
			bool viewOf = ViewTapping(ViewStates.Index);
            return View(employees.ToList());
        }
		#endregion

		#region Index Find - Commented
		/*
        [OutputCache(CacheProfile = "Year")]
        public ActionResult Index(System.Int32 id) {
            var employees = db.Employees.Include(e => e.Employee2).Where(n=> n. == id);
			bool viewOf = ViewTapping(ViewStates.Index);
            return View(employees.ToList());
        }
		*/
		#endregion

		#region Details
        public ActionResult Details(System.Int32 id) {
        
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
			bool viewOf = ViewTapping(ViewStates.Details, employee);
            return View(employee);
        }
		#endregion

		#region Create or Add
        public ActionResult Create() {        
			//GetDropDowns();
			bool viewOf = ViewTapping(ViewStates.Create);
            return View();
        }

		/*
		public ActionResult Create(System.Int32 id) {        
			GetDropDowns(id); // Generate hidden.
			bool viewOf = ViewTapping(ViewStates.Create);
            return View();
        }
		*/

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Employee employee) {
			bool viewOf = ViewTapping(ViewStates.CreatePostBefore, employee);
			//GetDropDowns(employee);
            if (ModelState.IsValid) {            
                db.Employees.Add(employee);
                bool state = SaveDatabase(ViewStates.Create, employee);
				if (state) {			
					AppVar.SetSavedStatus(ViewBag, CreatedSaved); // Saved Successfully.
				} else {					
					AppVar.SetErrorStatus(ViewBag, CreatedError); // Failed to save
				}
				
                viewOf = ViewTapping(ViewStates.CreatePostAfter, employee,state);
                return View(employee);
            }
            viewOf = ViewTapping(ViewStates.CreatePostAfter, employee, false);			
			AppVar.SetErrorStatus(ViewBag, CreatedError); // record is not valid for creation
            return View(employee);
        }
		#endregion

        #region Edit or modify record
        public ActionResult Edit(System.Int32 id) {
        
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
			bool viewOf = ViewTapping(ViewStates.Edit, employee);
			//GetDropDowns(employee); // Generating drop downs
            return View(employee);
        }

        
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Employee employee) {
			bool viewOf = ViewTapping(ViewStates.EditPostBefore, employee);
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                bool state = SaveDatabase(ViewStates.Edit, employee);
				if (state) {
                    AppVar.SetSavedStatus(ViewBag, EditedSaved); // Saved Successfully.
				} else {					
					AppVar.SetErrorStatus(ViewBag, EditedError); // Failed to Save
				}
				
                viewOf = ViewTapping(ViewStates.EditPostAfter, employee , state);
                return RedirectToAction("Index");
            }
            viewOf = ViewTapping(ViewStates.EditPostAfter, employee , false);
        	//GetDropDowns(employee);
            AppVar.SetErrorStatus(ViewBag, EditedError); // record not valid for save
            return View(employee);
        }
		#endregion

		#region Delete or remove record

		
        public ActionResult Delete(int id) {
        
            var employee = db.Employees.Find(id);
            bool viewOf = ViewTapping(ViewStates.Delete, employee);
			return View(employee);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]		
        public ActionResult DeleteConfirmed(int id) {
            var employee = db.Employees.Find(id);
			bool viewOf = ViewTapping(ViewStates.DeletePost, employee);
            db.Employees.Remove(employee);
            bool state = SaveDatabase(ViewStates.Delete, employee);
			if (!state) {			
				AppVar.SetErrorStatus(ViewBag, DeletedError); // Failed to Save				
                return View(employee);
			}
			
            return RedirectToAction("Index");
        }
		#endregion

		#region Removing output cache
		public void RemoveOutputCache(string url) {
			HttpResponse.RemoveOutputCacheItem(url);
		}
        
        public void RemoveOutputCacheOnIndex() {
            var cacheManager = new OutputCacheManager();
            cacheManager.RemoveItems(ControllerName, "Index");
            cacheManager.RemoveItems(ControllerName, "List");
            cacheManager = null;
            GC.Collect();
        }
		#endregion
    }

	
}
