//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertiseRequest
    {
        public AdvertiseRequest()
        {
            this.AdvertisePaymentConfirmeds = new HashSet<AdvertisePaymentConfirmed>();
        }
    
        public long AdvertiseRequestID { get; set; }
        public System.DateTime Started { get; set; }
        public System.DateTime Ended { get; set; }
        public long AdvertiseID { get; set; }
        public byte DaysToShow { get; set; }
        public decimal GeneratedPayment { get; set; }
        public byte DaysToAdded { get; set; }
        public bool IsPaymentVerified { get; set; }
    
        public virtual Advertise Advertise { get; set; }
        public virtual ICollection<AdvertisePaymentConfirmed> AdvertisePaymentConfirmeds { get; set; }
    }
}
