//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Article1 = new HashSet<Article>();
            this.Article11 = new HashSet<Article>();
            this.DraftLogs = new HashSet<DraftLog>();
            this.Keywords = new HashSet<Keyword>();
            this.MediaArticleRelations = new HashSet<MediaArticleRelation>();
            this.ModifyLogs = new HashSet<ModifyLog>();
            this.RelatedArticles = new HashSet<RelatedArticle>();
            this.RelatedArticles1 = new HashSet<RelatedArticle>();
            this.SendArticles = new HashSet<SendArticle>();
            this.URLs = new HashSet<URL>();
        }
    
        public long ArticleID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Page1 { get; set; }
        public string Page2 { get; set; }
        public string Page3 { get; set; }
        public string Page4 { get; set; }
        public int CategoryID { get; set; }
        public Nullable<long> FeatureMediaID { get; set; }
        public System.DateTime PublishDate { get; set; }
        public byte ArticleStateID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long WrittenByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public string MetaDescription1 { get; set; }
        public string MetaDescription2 { get; set; }
        public Nullable<long> VerifiedByUserID { get; set; }
        public Nullable<long> OriginalArticleID { get; set; }
        public long TotalViewed { get; set; }
        public byte LastModifiedCount { get; set; }
        public long ThumbsUp { get; set; }
        public Nullable<long> NextPageArticleID { get; set; }
        public byte LanguageID { get; set; }
        public bool IsVerified { get; set; }
        public bool IsProblematic { get; set; }
        public bool IsSendByUser { get; set; }
        public bool IsInDefaultLanguage { get; set; }
        public bool IsCommentsEnabled { get; set; }
        public bool IsReportedFromAnySource { get; set; }
        public bool IsReportActionSolved { get; set; }
        public bool IsAnyDraftExist { get; set; }
        public bool IsPreviousPageExist { get; set; }
        public bool IsNextPageExist { get; set; }
    
        public virtual ICollection<Article> Article1 { get; set; }
        public virtual Article Article2 { get; set; }
        public virtual ICollection<Article> Article11 { get; set; }
        public virtual Article Article3 { get; set; }
        public virtual ArticleState ArticleState { get; set; }
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<DraftLog> DraftLogs { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
        public virtual ICollection<MediaArticleRelation> MediaArticleRelations { get; set; }
        public virtual ICollection<ModifyLog> ModifyLogs { get; set; }
        public virtual ICollection<RelatedArticle> RelatedArticles { get; set; }
        public virtual ICollection<RelatedArticle> RelatedArticles1 { get; set; }
        public virtual ICollection<SendArticle> SendArticles { get; set; }
        public virtual ICollection<URL> URLs { get; set; }
    }
}
