//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public Medium()
        {
            this.Advertises = new HashSet<Advertise>();
            this.Articles = new HashSet<Article>();
            this.MediaArticleRelations = new HashSet<MediaArticleRelation>();
        }
    
        public long MediaID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public short FileTypeID { get; set; }
        public string EmbedHTML { get; set; }
        public bool IsVideo { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
    
        public virtual ICollection<Advertise> Advertises { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Category Category { get; set; }
        public virtual FileType FileType { get; set; }
        public virtual ICollection<MediaArticleRelation> MediaArticleRelations { get; set; }
    }
}
