//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyObtained
    {
        public long MoneyObtainedID { get; set; }
        public long UserID { get; set; }
        public decimal MoneyAmount { get; set; }
        public decimal XPUsed { get; set; }
        public System.DateTime Dated { get; set; }
        public bool IsMoneyReceivedByUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
