//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify
    {
        public long NotifyID { get; set; }
        public Nullable<long> ToUserID { get; set; }
        public Nullable<long> FromWhomUserID { get; set; }
        public string Description { get; set; }
        public byte NotificationTypeID { get; set; }
        public System.DateTime Dated { get; set; }
        public byte ToUserRoleID { get; set; }
        public bool IsImportant { get; set; }
        public bool IsGlobal { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
