//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationType
    {
        public NotificationType()
        {
            this.Notifies = new HashSet<Notify>();
        }
    
        public byte NotificationTypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Notify> Notifies { get; set; }
    }
}
