//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.AdvertisePaymentConfirmeds = new HashSet<AdvertisePaymentConfirmed>();
        }
    
        public byte PaymentMethodID { get; set; }
        public string PaymentType { get; set; }
    
        public virtual ICollection<AdvertisePaymentConfirmed> AdvertisePaymentConfirmeds { get; set; }
    }
}
