//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPaid
    {
        public long SalaryPaidID { get; set; }
        public long UserID { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<int> PaidYear { get; set; }
        public Nullable<int> PaidMonth { get; set; }
        public decimal AmountPaid { get; set; }
    
        public virtual User User { get; set; }
    }
}
