//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSearchingArticle
    {
        public long ArticleID { get; set; }
        public string FullSearhingtext { get; set; }
        public System.DateTime PublishDate { get; set; }
        public long TotalViewed { get; set; }
    }
}
