//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XPGainedType
    {
        public XPGainedType()
        {
            this.Points = new HashSet<Point>();
        }
    
        public short XPGainedTypeID { get; set; }
        public string XPTypeName { get; set; }
        public double PointForThisType { get; set; }
    
        public virtual ICollection<Point> Points { get; set; }
    }
}
