//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class AdvertiseType
    {
        public AdvertiseType()
        {
            this.Advertises = new HashSet<Advertise>();
        }
    
        public byte AdvertiseTypeID { get; set; }
        public string TypeName { get; set; }
        public decimal AmountRequired { get; set; }
    
        public virtual ICollection<Advertise> Advertises { get; set; }
    }
}
