//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class ArticleState
    {
        public ArticleState()
        {
            this.Articles = new HashSet<Article>();
            this.ModifyLogs = new HashSet<ModifyLog>();
        }
    
        public byte ArticleStateID { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<ModifyLog> ModifyLogs { get; set; }
    }
}
