//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class Category
    {
        public Category()
        {
            this.Articles = new HashSet<Article>();
            this.MediaFiles = new HashSet<MediaFile>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryDisplay { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<MediaFile> MediaFiles { get; set; }
    }
}
