//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class FileType
    {
        public FileType()
        {
            this.MediaFiles = new HashSet<MediaFile>();
        }
    
        public short FileTypeID { get; set; }
        public string TypeOfFile { get; set; }
    
        public virtual ICollection<MediaFile> MediaFiles { get; set; }
    }
}
