//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class Level
    {
        public Level()
        {
            this.Users = new HashSet<User>();
        }
    
        public short LevelID { get; set; }
        public string LevelRepresentation { get; set; }
        public decimal MinPoints { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
