//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class SalaryType
    {
        public SalaryType()
        {
            this.Users = new HashSet<User>();
        }
    
        public byte SalaryTypeID { get; set; }
        public string SalaryTypeName { get; set; }
        public decimal MonthlySalary { get; set; }
        public bool IsMonthlyCheck { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
