//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class TimeZone
    {
        public TimeZone()
        {
            this.Users = new HashSet<User>();
        }
    
        public short TimeZoneID { get; set; }
        public string TimeZoneInfoID { get; set; }
        public string TimeZoneDisplay { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
