//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class URL
    {
        public long URLID { get; set; }
        public string Domain { get; set; }
        public string Otherpart1 { get; set; }
        public string Otherpart2 { get; set; }
        public string Otherpart3 { get; set; }
        public string LinkDisplay { get; set; }
        public long ArticleID { get; set; }
        public string FriendlyText { get; set; }
        public string AlsoKnownAs { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
