//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class UserRole
    {
        public UserRole()
        {
            this.Notifies = new HashSet<Notify>();
            this.Users = new HashSet<User>();
            this.UserRole1 = new HashSet<UserRole>();
        }
    
        public byte UserRoleID { get; set; }
        public string Role { get; set; }
        public byte Priority { get; set; }
        public int XPRequired { get; set; }
        public bool CanAqurieByXP { get; set; }
        public Nullable<byte> NestedRoleID { get; set; }
    
        public virtual ICollection<Notify> Notifies { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<UserRole> UserRole1 { get; set; }
        public virtual UserRole UserRole2 { get; set; }
    }
}
