//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DevBootstrapper.Models.EntityModel.POCO
{
    public partial class User
    {
        public User()
        {
            this.Advertises = new HashSet<Advertise>();
            this.AdvertisePaymentConfirmeds = new HashSet<AdvertisePaymentConfirmed>();
            this.AdvertisePaymentConfirmeds1 = new HashSet<AdvertisePaymentConfirmed>();
            this.Articles = new HashSet<Article>();
            this.Articles1 = new HashSet<Article>();
            this.Articles2 = new HashSet<Article>();
            this.Comments = new HashSet<Comment>();
            this.ModifyLogs = new HashSet<ModifyLog>();
            this.MoneyObtaineds = new HashSet<MoneyObtained>();
            this.NotifiedRelations = new HashSet<NotifiedRelation>();
            this.Notifies = new HashSet<Notify>();
            this.Notifies1 = new HashSet<Notify>();
            this.Points = new HashSet<Point>();
            this.ProfileBasedSearches = new HashSet<ProfileBasedSearch>();
            this.SalaryPaids = new HashSet<SalaryPaid>();
            this.SendArticles = new HashSet<SendArticle>();
            this.SendArticles1 = new HashSet<SendArticle>();
        }
    
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public short TimeZoneID { get; set; }
        public byte UserRoleID { get; set; }
        public decimal TotalXP { get; set; }
        public short LevelID { get; set; }
        public decimal LeftXPToTrade { get; set; }
        public byte SalaryTypeID { get; set; }
        public System.DateTime JoinedDate { get; set; }
        public System.DateTime LastVisited { get; set; }
        public System.DateTime StartingSalaryDate { get; set; }
        public bool IsEmployee { get; set; }
    
        public virtual ICollection<Advertise> Advertises { get; set; }
        public virtual ICollection<AdvertisePaymentConfirmed> AdvertisePaymentConfirmeds { get; set; }
        public virtual ICollection<AdvertisePaymentConfirmed> AdvertisePaymentConfirmeds1 { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Article> Articles1 { get; set; }
        public virtual ICollection<Article> Articles2 { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Level Level { get; set; }
        public virtual ICollection<ModifyLog> ModifyLogs { get; set; }
        public virtual ICollection<MoneyObtained> MoneyObtaineds { get; set; }
        public virtual ICollection<NotifiedRelation> NotifiedRelations { get; set; }
        public virtual ICollection<Notify> Notifies { get; set; }
        public virtual ICollection<Notify> Notifies1 { get; set; }
        public virtual ICollection<Point> Points { get; set; }
        public virtual ICollection<ProfileBasedSearch> ProfileBasedSearches { get; set; }
        public virtual ICollection<SalaryPaid> SalaryPaids { get; set; }
        public virtual SalaryType SalaryType { get; set; }
        public virtual ICollection<SendArticle> SendArticles { get; set; }
        public virtual ICollection<SendArticle> SendArticles1 { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
